# Generated by Django 3.1.7 on 2021-11-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211101_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], default='petrol', max_length=30)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='car',
            name='property',
            field=models.ManyToManyField(to='cars.Property'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[('straight', 'Straight'), ('inline', 'Inline'), ('flat', 'Flat'), ('v', 'V')], default='straight', max_length=75),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_case',
            field=models.CharField(choices=[('mechanical', 'Mechanical'), ('automatic', 'Automatic'), ('variator', 'Variator'), ('robotic', 'Robotic')], default='automatic', max_length=75),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.fueltype'),
        ),
    ]
