# Generated by Django 3.1.7 on 2021-11-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211122_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='fuel_type',
            new_name='fueltype',
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.fueltype'),
        ),
    ]
